[32m2024-04-04 20:16:42 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 841639de-973c-42c0-924c-c903e0016368 - 49529 - LOGS_CAPTURED - Started capturing logs in process (pid: 49529).
[32m2024-04-04 20:16:42 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 841639de-973c-42c0-924c-c903e0016368 - 49529 - ncaa_rankings - STEP_START - Started execution of step "ncaa_rankings".
[32m2024-04-04 20:16:42 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 841639de-973c-42c0-924c-c903e0016368 - 49529 - ncaa_rankings - STEP_OUTPUT - Yielded output "result" of type "DataFrame". Warning! Type check failed.
[32m2024-04-04 20:16:42 -0500[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 841639de-973c-42c0-924c-c903e0016368 - 49529 - ncaa_rankings - STEP_FAILURE - Execution of step "ncaa_rankings" failed.

dagster._core.errors.DagsterTypeCheckDidNotPass: Type check failed for step output "result" - expected type "DataFrame". Description: Value of type <class 'NoneType'> failed type check for Dagster type DataFrame, expected value to be of Python type pandas.core.frame.DataFrame.

Stack Trace:
  File "/Users/isaacanderson/anaconda3/envs/boo/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_plan.py", line 286, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/Users/isaacanderson/anaconda3/envs/boo/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 532, in core_dagster_event_sequence_for_step
    for evt in _type_check_and_store_output(step_context, user_event):
  File "/Users/isaacanderson/anaconda3/envs/boo/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 584, in _type_check_and_store_output
    for output_event in _type_check_output(step_context, step_output_handle, output, version):
  File "/Users/isaacanderson/anaconda3/envs/boo/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 452, in _type_check_output
    raise DagsterTypeCheckDidNotPass(
[0m
