[32m2024-04-23 15:45:18 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 75dc69d6-1526-476d-a28c-5ac9a59ae004 - 65367 - LOGS_CAPTURED - Started capturing logs in process (pid: 65367).
[32m2024-04-23 15:45:18 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 75dc69d6-1526-476d-a28c-5ac9a59ae004 - 65367 - ncaa_rankings - STEP_START - Started execution of step "ncaa_rankings".
[32m2024-04-23 15:45:18 -0500[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 75dc69d6-1526-476d-a28c-5ac9a59ae004 - 65367 - ncaa_rankings - STEP_FAILURE - Execution of step "ncaa_rankings" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "ncaa_rankings"::

OSError: Cannot save file into a non-existent directory: '/Users/isaacanderson/Desktop/CSE314/MarchMadness/data/raw/processed'

Stack Trace:
  File "/Users/isaacanderson/anaconda3/envs/boo/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/isaacanderson/anaconda3/envs/boo/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 464, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Users/isaacanderson/anaconda3/envs/boo/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 141, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/Users/isaacanderson/anaconda3/envs/boo/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 129, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/Users/isaacanderson/Desktop/CSE314/MarchMadness/projectDag/projectDag/assets/RawData/__init__.py", line 18, in ncaa_rankings
    df.to_csv(f'{DATA_FOLDER}/processed/concatenated_data.csv', index = False)
  File "/Users/isaacanderson/anaconda3/envs/boo/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isaacanderson/anaconda3/envs/boo/lib/python3.12/site-packages/pandas/core/generic.py", line 3964, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isaacanderson/anaconda3/envs/boo/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/Users/isaacanderson/anaconda3/envs/boo/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/Users/isaacanderson/anaconda3/envs/boo/lib/python3.12/site-packages/pandas/io/common.py", line 749, in get_handle
    check_parent_directory(str(handle))
  File "/Users/isaacanderson/anaconda3/envs/boo/lib/python3.12/site-packages/pandas/io/common.py", line 616, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
[0m
